FROM wordpress:6.2.2-php8.1-apache
MAINTAINER MAINTAINER Ilnaz Mingazov <i.mingazov@ntechlab.com>
LABEL author=MingazovIG
RUN apt-get update
RUN apt-get install -y mysql-server
RUN apt-get install -y mysql-client
ENV DEBIAN_FRONTEND=noninteractive
#RUN apt-get update && ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && dpkg-reconfigure -f noninteractive tzdata
# Set timezone:
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone

# Install dependencies:
RUN apt-get update && apt-get install -y tzdata
#ENV TZ="America/New_York"
RUN apt-get install -y wordpress
RUN apt-get clean && rm -rf /var/logapt/lists/*
ENV MYSQL_DATABASE=exampledb
ENV MYSQL_USER=exampleuser
ENV MYSQL_PASSWORD=examplepass
ENV MYSQL_RANDOM_ROOT_PASSWORD='1'
ENV WORDPRESS_DB_HOST=127.0.0.1:3306
ENV WORDPRESS_DB_USER=exampleuser
ENV WORDPRESS_DB_PASSWORD=examplepass
ENV WORDPRESS_DB_NAME=exampledb
EXPOSE 3306
EXPOSE 80

CMD ["apache2-foreground"]
#CMD ["wp", "shell"]
#CMD ["mysqld"]
